<?php

declare(strict_types=1);

namespace Tests\Unit\Services;

use Mockery;
use Exception;
use ReflectionProperty;
use Tests\TestCase;
use App\Services\YoutubeService;
use Google\Service\YouTube;
use Google\Service\YouTube\Caption;
use Google\Service\YouTube\CaptionSnippet;
use Google\Service\YouTube\Resource\Captions;
use Google\Service\YouTube\CaptionListResponse;

/**
 * YoutubeService::hasCaptionTracks() —— 公開字幕閘門的判斷本體。
 *
 * captions.list 一律 mock，測試不對外發請求。trackKind 的值取自 2026-10-03 對
 * 公開影片的實測：作者上傳的是 standard、自動產生的是 asr（例如 9bZkp7q19f0
 * 只有一條 asr ko），兩者都要算「有字幕」。
 *
 * @internal
 * @coversNothing
 */
class YoutubeServiceCaptionTracksTest extends TestCase
{
    private const VIDEO_ID = '9bZkp7q19f0';

    /**
     * @param list<array{0: string, 1?: string}>|Exception $tracks 每條是 [trackKind, status]
     */
    private function service(array|Exception $tracks): YoutubeService
    {
        $captions = Mockery::mock(Captions::class);
        $expectation = $captions->shouldReceive('listCaptions')->with('snippet', self::VIDEO_ID);

        if ($tracks instanceof Exception) {
            $expectation->andThrow($tracks);
        } else {
            $response = new CaptionListResponse();
            $response->setItems(array_map(function (array $track) {
                $snippet = new CaptionSnippet();
                $snippet->setTrackKind($track[0]);
                $snippet->setStatus($track[1] ?? 'serving');

                $caption = new Caption();
                $caption->setSnippet($snippet);

                return $caption;
            }, $tracks));
            $expectation->andReturn($response);
        }

        $service = new YoutubeService();
        $youtube = (new ReflectionProperty(YoutubeService::class, 'youtube'))->getValue($service);
        $this->assertInstanceOf(YouTube::class, $youtube);
        $youtube->captions = $captions;

        return $service;
    }

    public function testAutoGeneratedCaptionsCount(): void
    {
        $this->assertTrue($this->service([['asr']])->hasCaptionTracks(self::VIDEO_ID));
    }

    public function testUploadedCaptionsCount(): void
    {
        $this->assertTrue($this->service([['standard']])->hasCaptionTracks(self::VIDEO_ID));
    }

    public function testNoTracksMeansNoCaptions(): void
    {
        $this->assertFalse($this->service([])->hasCaptionTracks(self::VIDEO_ID));
    }

    public function testForcedTrackAloneDoesNotCount(): void
    {
        // forced 只翻片中的外語片段，不是整支影片的字幕。
        $this->assertFalse($this->service([['forced']])->hasCaptionTracks(self::VIDEO_ID));
    }

    public function testFailedTrackDoesNotCount(): void
    {
        // 處理失敗的軌道沒有內容可看。
        $this->assertFalse($this->service([['asr', 'failed']])->hasCaptionTracks(self::VIDEO_ID));
    }

    public function testApiErrorIsUnknownRatherThanNoCaptions(): void
    {
        $this->assertNull(
            $this->service(new Exception('quotaExceeded'))->hasCaptionTracks(self::VIDEO_ID)
        );
    }
}
